name: Test Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run unit tests
        run: python -m unittest discover -s . -p "testCalculator.py"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy application
        run: echo "Deploying application..."
